-- Rank donors by age (highest first)
SELECT DONOR_NAME, AGE,
RANK() OVER (ORDER BY AGE DESC) AS RANKING
FROM BLOOD_GROUP;

-- Dense Rank
SELECT DONOR_NAME, AGE,
DENSE_RANK() OVER (ORDER BY AGE DESC) AS DENSE_RANKING
FROM BLOOD_GROUP;

-- Row Number
SELECT DONOR_NAME, AGE,
ROW_NUMBER() OVER (ORDER BY AGE) AS ROW_NUM
FROM BLOOD_GROUP;

-- Running Total of age
SELECT DONOR_ID, AGE,
SUM(AGE) OVER (ORDER BY DONOR_ID) AS RUNNING_TOTAL
FROM BLOOD_GROUP;

-- Previous value (LAG)
SELECT DONOR_ID, AGE,
LAG(AGE) OVER (ORDER BY AGE) AS PREVIOUS_AGE
FROM BLOOD_GROUP;

-- Next value (LEAD)
SELECT DONOR_ID, AGE,
LEAD(AGE) OVER (ORDER BY AGE) AS NEXT_AGE
FROM BLOOD_GROUP;

-- Second highest age
SELECT MAX(AGE)
FROM BLOOD_GROUP
WHERE AGE < (SELECT MAX(AGE) FROM BLOOD_GROUP);
