-- DDL COMMANDS

ALTER TABLE BLOOD_GROUP ADD EMAIL VARCHAR2(30);
ALTER TABLE BLOOD_GROUP MODIFY DONOR_NAME VARCHAR2(50);

RENAME BLOOD_GROUP TO BLOOD_DONORS;

TRUNCATE TABLE BLOOD_DONORS;

-- DROP TABLE BLOOD_DONORS;

-- DML

UPDATE BLOOD_GROUP SET AGE = AGE + 1;
DELETE FROM BLOOD_GROUP WHERE AGE < 25;

-- TCL

SAVEPOINT A;
UPDATE BLOOD_GROUP SET AGE = 40 WHERE DONOR_ID = 1;
ROLLBACK TO A;
COMMIT;

-- DCL

GRANT SELECT ON BLOOD_GROUP TO USER1;
REVOKE SELECT ON BLOOD_GROUP FROM USER1;

-- OPERATORS

SELECT AGE + 5 FROM BLOOD_GROUP;
SELECT * FROM BLOOD_GROUP WHERE AGE > 25;
SELECT * FROM BLOOD_GROUP WHERE AGE > 25 AND CITY='HYD';

SELECT DONOR_ID FROM BLOOD_GROUP
UNION
SELECT DONOR_ID FROM BLOOD_GROUP;

SELECT DONOR_ID FROM BLOOD_GROUP
INTERSECT
SELECT DONOR_ID FROM BLOOD_GROUP;

SELECT DONOR_ID FROM BLOOD_GROUP
MINUS
SELECT DONOR_ID FROM BLOOD_GROUP;

-- CHARACTER FUNCTIONS

SELECT UPPER(DONOR_NAME) FROM BLOOD_GROUP;
SELECT LOWER(DONOR_NAME) FROM BLOOD_GROUP;
SELECT INITCAP(DONOR_NAME) FROM BLOOD_GROUP;

SELECT LPAD(DONOR_NAME,10,'*') FROM BLOOD_GROUP;
SELECT RPAD(DONOR_NAME,10,'*') FROM BLOOD_GROUP;

SELECT LENGTH(DONOR_NAME) FROM BLOOD_GROUP;

SELECT REPLACE(DONOR_NAME,'A','X') FROM BLOOD_GROUP;

SELECT SUBSTR(DONOR_NAME,1,3) FROM BLOOD_GROUP;

SELECT INSTR(DONOR_NAME,'A') FROM BLOOD_GROUP;

SELECT TRIM('  SANA  ') FROM DUAL;

-- NULL FUNCTIONS

SELECT NVL(NULL, 'NO DATA') FROM DUAL;
SELECT NVL2(NULL, 'NOT NULL', 'IS NULL') FROM DUAL;

-- DATE FUNCTIONS

SELECT SYSDATE FROM DUAL;
SELECT CURRENT_DATE FROM DUAL;

SELECT TO_DATE('2024-01-01','YYYY-MM-DD') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'DD-MM-YYYY') FROM DUAL;

SELECT ADD_MONTHS(SYSDATE,2) FROM DUAL;

SELECT MONTHS_BETWEEN(SYSDATE, TO_DATE('2023-01-01','YYYY-MM-DD')) FROM DUAL;

SELECT TRUNC(SYSDATE) FROM DUAL;

SELECT NEXT_DAY(SYSDATE,'MONDAY') FROM DUAL;

-- PSEUDO COLUMNS

SELECT ROWNUM, DONOR_NAME FROM BLOOD_GROUP;
SELECT ROWID FROM BLOOD_GROUP;

-- BACKUP

CREATE TABLE BG_BACKUP AS SELECT * FROM BLOOD_GROUP;
CREATE TABLE BG_STRUCTURE AS SELECT * FROM BLOOD_GROUP WHERE 1=0;

-- CONSTRAINTS

CREATE TABLE BG_NEW (
  ID NUMBER PRIMARY KEY,
  NAME VARCHAR2(20) NOT NULL,
  BLOOD_TYPE VARCHAR2(3) UNIQUE,
  AGE NUMBER CHECK (AGE > 18)
);

CREATE TABLE BG_REF (
  ID NUMBER,
  BG_ID NUMBER,
  CONSTRAINT FK_BG FOREIGN KEY (BG_ID)
  REFERENCES BG_NEW(ID)
);

-- PARTITION

SELECT BLOOD_TYPE, AGE,
RANK() OVER (PARTITION BY BLOOD_TYPE ORDER BY AGE DESC)
FROM BLOOD_GROUP;

-- SELF JOIN

SELECT A.DONOR_NAME, B.DONOR_NAME
FROM BLOOD_GROUP A, BLOOD_GROUP B
WHERE A.DONOR_ID = B.DONOR_ID;

-- NON-EQUI JOIN

SELECT *
FROM BLOOD_GROUP A, BLOOD_GROUP B
WHERE A.AGE > B.AGE;

-- DELETE vs TRUNCATE vs DROP

DELETE FROM BLOOD_GROUP;
-- TRUNCATE TABLE BLOOD_GROUP;
-- ===============================
-- ADDITIONAL REQUIRED TOPICS
-- ===============================

-- INSERT METHODS

-- Method 1: Full insert
INSERT INTO BLOOD_GROUP VALUES (10,'TEST',25,'A+','HYD',1,SYSDATE);

-- Method 2: Selected columns
INSERT INTO BLOOD_GROUP (DONOR_ID, DONOR_NAME)
VALUES (11,'TEST2');

-- Method 3: From another table
INSERT INTO BLOOD_GROUP
SELECT * FROM BG_BACKUP;

-- ALIAS

SELECT DONOR_NAME AS NAME FROM BLOOD_GROUP;

-- DIFFERENCE NOTES

-- DELETE: removes rows (can rollback)
-- TRUNCATE: removes all rows (cannot rollback)
-- DROP: deletes table completely

-- CONSTRAINT DIFFERENCE

-- PRIMARY KEY: unique + not null
-- UNIQUE: allows null
-- NOT NULL: only prevents null values
-- Date usage with table

SELECT DONOR_NAME, DONATION_DATE,
ADD_MONTHS(DONATION_DATE, 1) AS NEXT_DONATION
FROM BLOOD_GROUP;
-- DROP TABLE BLOOD_GROUP;
-- Date usage with table
-- CONSTRAINT DIFFERENCE

-- PRIMARY KEY: unique + not null
-- UNIQUE: allows null
-- NOT NULL: only prevents null values

-- Date usage with table

