INSERT INTO BLOOD_GROUP VALUES (1,'SANA',23,'A+','HYD',2,SYSDATE);
INSERT INTO BLOOD_GROUP VALUES (2,'RAM',25,'B+','BLR',1,SYSDATE);
INSERT INTO BLOOD_GROUP VALUES (3,'RAJU',30,'O+','CHN',3,SYSDATE);
INSERT INTO BLOOD_GROUP VALUES (4,'ANU',22,'AB+','HYD',2,SYSDATE);
INSERT INTO BLOOD_GROUP VALUES (5,'KIRAN',28,'A-','BLR',4,SYSDATE);
INSERT INTO BLOOD_GROUP VALUES (6,'MEENA',26,'O-','CHN',1,SYSDATE);

COMMIT;
