-- Create city table
CREATE TABLE CITY_INFO (
  CITY VARCHAR2(20),
  STATE VARCHAR2(20)
);

-- Insert data into city table
INSERT INTO CITY_INFO VALUES ('HYD','TELANGANA');
INSERT INTO CITY_INFO VALUES ('BLR','KARNATAKA');
INSERT INTO CITY_INFO VALUES ('CHN','TAMILNADU');

-- Inner Join
SELECT B.DONOR_NAME, B.CITY, C.STATE
FROM BLOOD_GROUP B
INNER JOIN CITY_INFO C
ON B.CITY = C.CITY;

-- Left Join
SELECT B.DONOR_NAME, B.CITY, C.STATE
FROM BLOOD_GROUP B
LEFT JOIN CITY_INFO C
ON B.CITY = C.CITY;

-- Right Join
SELECT B.DONOR_NAME, B.CITY, C.STATE
FROM BLOOD_GROUP B
RIGHT JOIN CITY_INFO C
ON B.CITY = C.CITY;

-- Cross Join
SELECT * 
FROM BLOOD_GROUP 
CROSS JOIN CITY_INFO;
