-- View all records
SELECT * FROM BLOOD_GROUP;

-- Filter donors above age 25
SELECT * FROM BLOOD_GROUP WHERE AGE > 25;

-- Sort donors by age descending
SELECT * FROM BLOOD_GROUP ORDER BY AGE DESC;

-- Show unique cities
SELECT DISTINCT CITY FROM BLOOD_GROUP;

-- Group donors by blood type
SELECT BLOOD_TYPE, SUM(UNITS_DONATED)
FROM BLOOD_GROUP
GROUP BY BLOOD_TYPE;

-- Having condition
SELECT BLOOD_TYPE, SUM(UNITS_DONATED)
FROM BLOOD_GROUP
GROUP BY BLOOD_TYPE
HAVING SUM(UNITS_DONATED) > 2;
